create table param.ownership ( entity_name varchar(50) references param.entity(name), owner_column_id uuid not null, group_column_id uuid default null, unique (entity_name, owner_column_id));

alter table param.entity alter column stated drop default; update param.entity set stated = 1 where stated = 'y';update param.entity set stated = 0 where stated = 'n'; alter table param.entity alter column stated type boolean  USING stated::boolean; alter table param.entity alter column stated set default false::boolean;
alter table param.entity alter column owned drop default; update param.entity set owned = 1 where owned = 'y';update param.entity set owned = 0 where owned = 'n'; alter table param.entity alter column owned type boolean  USING owned::boolean; alter table param.entity alter column owned set default false::boolean;
alter table param.entity alter column versioned drop default; update param.entity set versioned = 1 where versioned = 'y';update param.entity set versioned = 0 where versioned = 'n'; alter table param.entity alter column versioned type boolean  USING versioned::boolean; alter table param.entity alter column versioned set default false::boolean;
alter table param.entity alter column historized drop default; update param.entity set historized = 1 where historized = 'y';update param.entity set historized = 0 where historized = 'n'; alter table param.entity alter column historized type boolean  USING historized::boolean; alter table param.entity alter column historized set default false::boolean;
alter table param.entity alter column audited drop default; update param.entity set audited = 1 where audited = 'y';update param.entity set audited = 0 where audited = 'n'; alter table param.entity alter column audited type boolean  USING audited::boolean; alter table param.entity alter column audited set default false::boolean;
alter table param.entity alter column stamped drop default; update param.entity set stamped = 1 where stamped = 'y';update param.entity set stamped = 0 where stamped = 'n'; alter table param.entity alter column stamped type boolean  USING stamped::boolean; alter table param.entity alter column stamped set default false::boolean;

insert into db.changelog (action) values ('20260923.entity_ownership.sql');
